# Site settings
title: Dev's Software Engineering Blog posts
email: --
description: # this means to ignore newlines until "baseurl:"
    I am Devendra Naga (programmer, gamer and an introvert).

url: "https://devendranaga.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  devnaga

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
